# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 50
    height: 50
  tracker-list:            #TrackerList参数,支持多个
  - 192.168.127.141:22122

server:
       port: 8888